apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsss
spec:
  selector:
    matchLabels:
      app: rsss
  replicas: 1
  template:
    metadata:
      labels:
        app: rsss
    spec:
      containers:
      - name: rsss
        image: ghcr.io/yammerjp/rsss
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
